spring.application.name=student-registration-mvc
spring.mvc.view.suffix=.jsp
spring.datasource.url=jdbc:mysql://localhost:3306/studentdb

spring.datasource.username=root

spring.datasource.password=RaNa@#1312$%

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true